clc; close all; clear;

addpath('./Functions')
addpath('./Functions/Visualization')
addpath('./Functions/PAC')

%%

ch_labels = ["Hippo", "Pulvinar(LP)", "DS(CPu)", "PFC"];
fs = 2000;         
cfg = struct(                              ...
    'fs',               2000,                    ...
    'n',                100,                    ...
    'n_ch',             length(ch_labels),     ...
    'is_saving',        0,                     ...
    'epoch_t_start',    0.5,                   ...
    'y_range',          [-1 1],            ...
    'epoch_time',       [0.5, 1],              ... 
    'prep_band',        [1 300],               ... 
    'run_idx',          1,                      ...
    'is_downsample',    0,                      ...
    'fs_down',          250,                     ...
    'selected_chs',     1:4,                  ...
    'comodu_lowBand',   [5, 13],                ...
    'comodu_highBand',  [20, 90],                ...
    'nbins',            18,                      ...
    'nperm',            50,                        ...
    'interval',         0.5 * fs,               ...
    'w_step',           0.1 * fs               ...
);

is_saving = 1;
f_gamma = [25, 45];
f_theta = [8, 11];

tf_method = ["CWT", "rihazcek"];
DataTime = ["Before_Entr", "After10_Entr", "After20_Entr"];
trial_type = ["All_trials", "target_trials", "std_trials"];
data_file_name1 = ["Before_", "After10days_", "After20days_"];
data_file_name2 = ["all_", "target_", "std_"];

for i=1:1
   for j=1:length(trial_type)
      
       BeforePath = strcat('..\Results\PAC_comodu\MI_method\', tf_method(i), ...
                            '\', "Before_Entr", '\', trial_type(j), '\', 'Before_', ...
                            data_file_name2(j), 'PACs_', tf_method(i), '.mat');
       After10Path = strcat('..\Results\PAC_comodu\MI_method\', tf_method(i), ...
                            '\', "After10_Entr", '\', trial_type(j), '\', 'After10days_', ...
                            data_file_name2(j), 'PACs_', tf_method(i), '.mat');
       After20Path = strcat('..\Results\PAC_comodu\MI_method\', tf_method(i), ...
                            '\', "After20_Entr", '\', trial_type(j), '\', 'After20days_', ...
                            data_file_name2(j), 'PACs_', tf_method(i), '.mat');
       PAC_Before = load(BeforePath);
       fieldNames = fieldnames(PAC_Before);
       PAC_Before = PAC_Before.(fieldNames{1});
       PAC_After10 = load(After10Path);
       fieldNames = fieldnames(PAC_After10);
       PAC_After10 = PAC_After10.(fieldNames{1});
       PAC_After20 = load(After20Path);
       fieldNames = fieldnames(PAC_After20);
       PAC_After20 = PAC_After20.(fieldNames{1});
       
       f_high = load(strcat('../Results/PAC_comodu/MI_method/', ...
                             tf_method(i), '/f_high_', tf_method(i), '.mat')).f_high;
       f_low = load(strcat('../Results/PAC_comodu/MI_method/', ...
                             tf_method(i), '/f_low_', tf_method(i), '.mat')).f_low;
       
       f_high_idx = find(abs(f_high - f_gamma(1)) < 10*1e-1) : find(abs(f_high - f_gamma(end)) < 10*1e-1);
       f_low_idx = find(abs(f_low - f_theta(1)) < 10*1e-1) : find(abs(f_low - f_theta(end)) < 10*1e-1);
    
       for m=1:4
           for n=1:4
               PAC_comodu = PAC_Before{m,n};
               PAC_1D_dyn_Before = squeeze(mean(PAC_comodu(f_low_idx, f_high_idx, :), ...
                                        [1, 2]));
               PAC_comodu = PAC_After10{m,n};
               PAC_1D_dyn_After10 = squeeze(mean(PAC_comodu(f_low_idx, f_high_idx, :), ...
                                        [1, 2]));
               PAC_comodu = PAC_After20{m,n};
               PAC_1D_dyn_After20 = squeeze(mean(PAC_comodu(f_low_idx, f_high_idx, :), ...
                                        [1, 2]));
               
               t_end = cfg.interval : cfg.w_step : 3000;
               t_end = t_end/2 - cfg.epoch_t_start*1000;
               t_start = (0 : cfg.w_step : 3000 - cfg.interval)+1;
               t_start = (t_start-1)/2 - cfg.epoch_t_start*1000;
               
               xlabels = cell(1,length(t_end));
               for t=1:length(t_end)
                  xlabels{t} = strcat('[', num2str(t_start(t)), ',', ...
                                      num2str(t_end(t)), ']');
               end
               figure;
               plot(PAC_1D_dyn_Before, 'linewidth', 2); hold on;
               plot(PAC_1D_dyn_After10, 'linewidth', 2);
               plot(PAC_1D_dyn_After20, 'linewidth', 2); hold off;
               xticklabels(xlabels);
               fig_title = strcat('PAC dynamic - ', ch_labels(m), '-to-', ch_labels(n), '-', ...
                                  'fgamma', num2str(f_gamma(1)), '-', num2str(f_gamma(2)), ...
                                  'ftheta', num2str(f_theta(1)), '-', num2str(f_theta(2)));
               title(fig_title)
               legend("Before Entr.", "After 10 days", "After 20 days")
               save_path = strcat('../Results/PAC_1D_dyn/', tf_method(i), '/', trial_type(j), '/', ...
                                  'fgamma', num2str(f_gamma(1)), '-', num2str(f_gamma(2)), ...
                                  'ftheta', num2str(f_theta(1)), '-', num2str(f_theta(2)), '/');
               if is_saving
                   save_fig(save_path, fig_title)
               end
           end
       end
   end
end


